# Generated by Django 5.2 on 2025-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_ingrediente_id_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ROLL', 'roll'), ('BEBESTIBLE', 'bebestible'), ('CEVICHE', 'ceviche'), ('HANDROLL', 'handroll'), ('SUSHIBURGER', 'sushiburger'), ('EXTRA', 'extra'), ('GOHAN', 'gohan')], default='ROLL', max_length=20),
            preserve_default=False,
        ),
    ]
