# Generated by Django 5.2 on 2025-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=4990, max_digits=10),
            preserve_default=False,
        ),
    ]
