# Generated by Django 5.2 on 2025-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_ingrediente_descripcion_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
