# Generated by Django 5.2 on 2025-04-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_insumo_ingrediente_disponible_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medidad',
            field=models.CharField(choices=[('KG', 'kg'), ('LT', 'lt')], default='kg', max_length=2),
            preserve_default=False,
        ),
    ]
