# Generated by Django 5.2 on 2025-04-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_insumo_unidad_medidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='unidad_medidad',
            new_name='unidad_medida',
        ),
    ]
