# Generated by Django 5.2 on 2025-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_unidad_medidad_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', '    g'), ('LT', 'lt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='insumos', to='inventario.insumo'),
        ),
    ]
