# Generated by Django 5.2 on 2025-04-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_insumo_unidad_medida_alter_inventario_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'kg'), ('LT', 'lt')], max_length=2),
        ),
    ]
