# Generated by Django 5.2 on 2025-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.CharField(choices=[('CLIENTE', 'cliente'), ('SISTEMA', 'sistema')], default='SISTEMA', max_length=50),
            preserve_default=False,
        ),
    ]
