# Generated by Django 5.2 on 2025-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(null=True, related_name='productos', to='inventario.ingrediente'),
        ),
    ]
