# Generated by Django 5.2 on 2025-04-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_producto_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos', to='inventario.ingrediente'),
        ),
    ]
