# Generated by Django 5.2 on 2025-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_producto_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'kg'), ('LT', 'lt'), ('UNIDAD', 'unidad')], max_length=10),
        ),
    ]
