# Generated by Django 5.2 on 2025-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ROLL', 'roll'), ('BEBESTIBLE', 'bebestible'), ('CEVICHE', 'ceviche'), ('HANDROLL', 'handroll'), ('SUSHIBURGER', 'sushiburger'), ('EXTRA', 'extra'), ('GOHAN', 'gohan'), ('TABLA', 'tabla'), ('PROMO', 'promo')], max_length=20),
        ),
    ]
