# Generated by Django 5.2 on 2025-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designa si el usuario puede iniciar sesión en este sitio de administración', verbose_name='staff status'),
        ),
    ]
