# Generated by Django 5.2 on 2025-06-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates wheter the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
