# Generated by Django 5.2 on 2025-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DELIVERY', 'delivery'), ('ADMINISTRADOR', 'administrador'), ('CLIENTE', 'cliente'), ('CAJERO', 'cajero')], default='cliente', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default=23232321, max_length=10, verbose_name='cellphone'),
            preserve_default=False,
        ),
    ]
