# Generated by Django 5.2 on 2025-04-23 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0010_alter_insumo_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('direccion', models.TextField(default='RETIRO LOCAL', max_length=200)),
                ('estado', models.CharField(choices=[('PREPARACION', 'preparacion'), ('REPARTO', 'reparto'), ('LISTO', 'listo'), ('ENTREGADO', 'entregado')], default='PREPARACION', max_length=20)),
                ('observacion', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
