# Generated by Django 5.2 on 2025-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_productos_alter_detallepedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(default='RETIRO LOCAL', max_length=200),
        ),
    ]
