# Generated by Django 5.2 on 2025-04-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(blank=True, default='RETIRO LOCAL', max_length=200),
        ),
    ]
