# Generated by Django 5.2 on 2025-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PREPARACION', 'preparacion'), ('REPARTO', 'reparto'), ('LISTO', 'listo'), ('ENTREGADO', 'entregado'), ('CANCELADO', 'cancelado')], default='PREPARACION', max_length=20),
        ),
    ]
